SELECT * FROM DBO.Sales

SELECT PAYMENTMETHOD , SUM(TOTALAMOUNT) AS [SUM OF TOTAL AMOUNT] FROM DBO.Sales
GROUP BY PaymentMethod


SELECT ProductID, PAYMENTMETHOD  , SUM(TOTALAMOUNT) AS [SUM OF TOTAL AMOUNT SALES] FROM DBO.Sales
GROUP BY ProductID , PaymentMethod 
ORDER BY ProductID ASC 