USE [SALES DATABASE]
SELECT * FROM TABLE1
SELECT * FROM TABLE2

SELECT * FROM TABLE1 LEFT JOIN table2 ON TABLE1.C1=TABLE2.C1

SELECT A.C1 , A.C2,B.C3 FROM TABLE1 A LEFT JOIN TABLE2 B ON A.C1 = B.C1

SELECT A.C1 , A.C2,B.C3 FROM TABLE1 A LEFT OUTER JOIN TABLE2 B ON A.C1 = B.C1 -- THIS WILL WORK SAME 