USE [SALES DATABASE]

SELECT * FROM table1
SELECT * FROM TABLE2

SELECT * FROM table1 RIGHT JOIN TABLE2 ON TABLE1.C1 = TABLE2.C1

SELECT A.C1 , B.C1 , B.C3 FROM table1 A RIGHT JOIN TABLE2 B ON A.C1 = B.C1

SELECT A.C1 , B.C1 , B.C3 FROM table1 A RIGHT OUTER JOIN TABLE2 B ON A.C1 = B.C1 -- THIS WILL WORK SAME



SELECT A.C1 , A.C2 , B.C3 FROM table1 A RIGHT JOIN TABLE2 B ON A.C1 = B.C1