USE [SALES DATABASE]
SELECT * FROM TABLE1
SELECT * FROM TABLE2

SELECT * FROM TABLE1 AS A INNER JOIN  TABLE1 AS B ON A.C1=B.C1

SELECT A.C1 , B.C2  FROM TABLE1 AS A INNER JOIN  TABLE1 AS B ON A.C1=B.C1


SELECT A.C1 , B.C2  FROM TABLE1 AS A JOIN  TABLE1 AS B ON A.C1=B.C1