-- OK THE QUESTION IS HAVE TO DELETE ROW 2 FROM THE TABLE T1
-- UPDATE MARKS +10 
-- ADD NEW COLUMN NAME STUDENT NAMES.
-- INSERT NEW VALUES IN NAME COLUMN 
-- FIND AVG OF MARKS
-- COUNT > 40 
-- ORDER BY desc TO MARKS

CREATE DATABASE SQL_PRATICE
USE SQL_PRATICE

--DROP TABLE T1

CREATE TABLE T1 (
ROLL_NO INT PRIMARY KEY ,
MARKS INT
)

INSERT INTO T1(ROLL_NO , MARKS)
VALUES(1,'10'),(2,'20'),(3,'30'),(4,'40')

SELECT * FROM T1


DELETE FROM T1 WHERE ROLL_NO = '2'
UPDATE T1 SET MARKS = MARKS + 10 WHERE ROLL_NO = 2
ALTER TABLE T1 ADD STUDENT_NAME VARCHAR (256) 
UPDATE T1 SET STUDENT_NAME = 'MAYANK' WHERE ROLL_NO= 1
UPDATE T1 SET STUDENT_NAME = 'RAJ' WHERE ROLL_NO = 2
UPDATE T1 SET STUDENT_NAME = 'OM' WHERE ROLL_NO = 3
UPDATE T1 SET STUDENT_NAME = 'SHIV' WHERE ROLL_NO = 4
SELECT AVG(MARKS) [AVG MARKS] FROM T1
SELECT * FROM T1 WHERE MARKS < 40

SELECT * from T1
ORDER BY MARKS desc

SELECT * FROM T1


